name: Static analysis for OWL to Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

  # Allow manual execution
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Set up JDK 18
    #  uses: actions/setup-java@v3
    #  with:
    #    java-version: '18'
    #    distribution: 'temurin'
    - name: Detekt all
      uses: natiginfo/action-detekt-all@1.20.0

